### ISSUE TITLE
Error flair-couchdb-couchdb in the output

### ISSUE THREAD

**Issue by fabiofilz** [viz-centric/flair-helm-charts#10]
Hi @admin-vizcentric,

Could you please check the error in the flair-couchdb-couchdb output?

Kind regards,
Fabio

`flair-couchdb-couchdb-2 couchdb [error] 2020-04-15T12:52:19.831394Z couchdb@flair-couchdb-couchdb-2.flair-couchdb-couchdb.flair.svc.cluster.local <0.261.0> -------- Could not get design docs for <<"shards/c0000000-dfffffff/_users.1586883558">> error:{badarg,[{ets,member,[mem3_openers,<<"_users">>],[]},{mem3_shards,maybe_spawn_shard_writer,3,[{file,"src/mem3_shards.erl"},{line,476}]},{mem3_shards,load_shards_from_db,2,[{file,"src/mem3_shards.erl"},{line,381}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,for_db,2,[{file,"src/mem3_shards.erl"},{line,59}]},{fabric_view_all_docs,go,5,[{file,"src/fabric_view_all_docs.erl"},{line,24}]},{couch_db,'-get_design_docs/1-fun-0-',1,[{file,"src/couch_db.erl"},{line,627}]}]}
flair-couchdb-couchdb-2 couchdb [error] 2020-04-15T12:52:19.831432Z couchdb@flair-couchdb-couchdb-2.flair-couchdb-couchdb.flair.svc.cluster.local emulator -------- Error in process <0.269.0> on node 'couchdb@flair-couchdb-couchdb-2.flair-couchdb-couchdb.flair.svc.cluster.local' with exit value:
flair-couchdb-couchdb-2 couchdb {badarg,[{ets,member,[mem3_openers,<<"_users">>],[]},{mem3_shards,maybe_spawn_shard_writer,3,[{file,"src/mem3_shards.erl"},{line,476}]},{mem3_shards,load_shards_from_db,2,[{file,"src/mem3_shards.erl"},{line,381}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,for_db,2,[{file,"src/mem3_shards.erl"},{line,59}]},{fabric_view_all_docs,go,5,[{file,"src/fabric_view_all_docs.erl"},{line,24}]},{couch_db,'-get_design_docs/1-fun-0-',1,[{file,"src/couch_db.erl"},{line,627}]}]}
f`

`flair-couchdb-couchdb-2 couchdb [notice] 2020-04-15T12:52:27.287847Z couchdb@flair-couchdb-couchdb-2.flair-couchdb-couchdb.flair.svc.cluster.local <0.598.0> -------- 127.0.0.1 - - PUT /_nodes/couchdb@flair-couchdb-couchdb-0.flair-couchdb-couchdb.flair.svc.cluster.local 409
flair-couchdb-couchdb-2 couchdb [error] 2020-04-15T12:52:27.287965Z couchdb@flair-couchdb-couchdb-2.flair-couchdb-couchdb.flair.svc.cluster.local <0.598.0> -------- httpd 409 error response:
flair-couchdb-couchdb-2 couchdb  {"error":"conflict","reason":"Document update conflict."}
flair-couchdb-couchdb-2 couchdb [notice] 2020-04-15T12:52:28.285542Z couchdb@flair-couchdb-couchdb-2.flair-couchdb-couchdb.flair.svc.cluster.local <0.629.0> df6dee951f 10.77.33.16:5984 10.77.32.90 undefined GET /_up 200 ok 0
`

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz ,

could you please tell us the steps to reproduce this error?

Best regards,
Vizcentric Team

**Comment by fabiofilz** [comment]
Hi @admin-vizcentric,

I executed:

1 - Deploying Flair-bi
helm upgrade --install --wait --namespace flair flair-registry ./flair-registry
helm upgrade --install --wait --namespace flair flair-engine ./flair-engine
helm upgrade --install --wait --namespace flair flair-cache ./flair-cache
helm upgrade --install --wait --namespace flair flair-notifications ./flair-notifications
helm upgrade --install --wait --namespace flair --values ./flair-couchdb/values.yaml flair-couchdb ./flair-couchdb/couchdb
helm upgrade --install --wait --namespace flair flair-bi ./flair-bi

2 - Created a Datasource, Dashboard and view

3 - After it, I execute "stern flair-couchdb-couchdb" and checked the log.

Kind regards,
Fabio

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz ,

This issue is related to https://github.com/apache/couchdb-docker/issues/54.

Make sure you create **_users**, **_replicator** and **_global_changes** tables.

Kind regards,
Vizcentric Team

**Comment by fabiofilz** [comment]
Fixed
